version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.6
  # system_packages: true
  install:
    # Install requirements as system packages using pip
    - requirements: docs/requirements.txt
    # Install launch-ros-sandbox using setuptools
    - method: setuptools
      path: .
