# Build the package under test from source, and all its dependencies, then run
# the tests of the package under test.
addons:
  apt:
    sources:
    - sourceline: 'deb http://packages.ros.org/ros2/ubuntu bionic main'
      key_url: 'https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc'
    packages:
    - curl
    - python-rosdep
    - python3-colcon-common-extensions
    - python3-vcstool
    # Fast-RTPS dependencies
    - libasio-dev
    - libtinyxml2-dev
    update: true
before_script:
- sudo rosdep init
- rosdep update
branches:
  only:
  - master
cache: apt
dist: bionic
git:
  clone: false
language: generic
script:
- mkdir -p ~/ros2_latest_launch_ros_sandbox_ws/src
- cd ~/ros2_latest_launch_ros_sandbox_ws
- curl https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos | vcs import src/
# The repo file for the repository needs to be generated on-the-fly to incorporate the
# custom repository URL and branch name, when a PR is being built.
- |
  vcs import src/ << EOF
  repositories:
    launch_ros_sandbox:
      type: git
      url: "https://github.com/${TRAVIS_REPO_SLUG}.git"
      version: "${TRAVIS_BRANCH}"
  EOF
# RTI_NC_LICENSE_ACCEPTED avoids the interactive prompt asking to accept the
# RTI Connext license.
# For "latest" builds, rosdep often misses some keys, adding "|| true", to
# ignore those failures, as it is often non-critical.
- RTI_NC_LICENSE_ACCEPTED=yes rosdep install -r --from-paths src --ignore-src --rosdistro eloquent -y || true
- colcon build --event-handlers console_cohesion+ --packages-up-to launch_ros_sandbox --symlink-install
- colcon test --event-handlers console_cohesion+ --packages-select launch_ros_sandbox --return-code-on-test-failure
sudo: true
