name: Lint launch_ros_sandbox
on:
  pull_request:

jobs:
  ament_lint:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, flake8, pep257]
    steps:
    - uses: actions/checkout@v1
    - uses: thomas-moulard/setup-ros2@0.0.3
    - uses: thomas-moulard/action-ros2-lint@0.0.1
      with:
        linter: ${{ matrix.linter }}
        package-name: launch_ros_sandbox
