name: Lint launch_ros_sandbox
on:
  pull_request:

jobs:
  ament_lint:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, flake8, pep257]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: ${{ matrix.linter }}
        package-name: launch_ros_sandbox
