name: Test launch_ros_sandbox
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour, to help detect flakiness and
    # broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: ros-tooling/setup-ros2@0.0.4
    - uses: ros-tooling/action-ros2-ci@0.0.3
      with:
        package-name: launch_ros_sandbox
    - uses: actions/upload-artifact@master
      with:
        name: colcon-logs
        path: ros2_ws/log
