name: Test launch_ros_sandbox
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour, to help detect flakiness and
    # broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [macOS-latest, ubuntu-18.04]
    steps:
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: launch_ros_sandbox
    - uses: codecov/codecov-action@v1
      # Prevent being rate limited by only reporting coverage from the Ubuntu
      # build.
      if: matrix.os == 'ubuntu-18.04'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ros_ws/src/launch_ros_sandbox/coverage.xml
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml
        fail_ci_if_error: true
    - uses: actions/upload-artifact@master
      with:
        name: colcon-logs-${{ matrix.os }}
        path: ros_ws/log

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      if: always()
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      if: always()
