name: Test launch_ros_sandbox
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour, to help detect flakiness and
    # broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: ros-tooling/setup-ros2@0.0.4
    - uses: ros-tooling/action-ros2-ci@0.0.3
      with:
        package-name: launch_ros_sandbox
    - name: Notify Chime chatroom (failure)
      uses: thomas-moulard/action-amazon-chime@master
      if: failure()
      with:
        message: |
          [${{ github.workflow }}][${{ github.event_name }}] :heavy_exclamation_mark: Test Failure
          Link to GitHub Action run: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
        webhook: ${{ secrets.chimeRoomWebhoolUrl }}
    - name: Notify Chime chatroom (success)
      uses: thomas-moulard/action-amazon-chime@master
      if: success()
      with:
        message: |
          [${{ github.workflow }}][${{ github.event_name }}] :heavy_exclamation_mark: Test Succeeded
          Link to GitHub Action run: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
        webhook: ${{ secrets.chimeRoomWebhoolUrl }}
