name: Test launch_ros_sandbox
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: thomas-moulard/setup-ros2@0.0.3
    - uses: thomas-moulard/action-ros2-ci@master
      with:
        package-name: launch_ros_sandbox
