name: Test launch_ros_sandbox
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour, to help detect flakiness and
    # broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [macOS-10.14, ubuntu-18.04]
    steps:
    - uses: ros-tooling/setup-ros2@tmoulard/fix-osx
    - uses: ros-tooling/action-ros2-ci@tmoulard/fix-osx
      with:
        package-name: launch_ros_sandbox
