name: Test launch_ros_sandbox
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour, to help detect flakiness and
    # broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test_macOS:
    runs-on: macOS-latest
    steps:
    - uses: ros-tooling/setup-ros@0.2.1
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: launch_ros_sandbox
        target-ros2-distro: rolling
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
    - uses: actions/upload-artifact@v2.3.0
      with:
        name: colcon-logs-macOS
        path: ros_ws/log

  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-latest
    steps:
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: launch_ros_sandbox
        target-ros2-distro: rolling
    - uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ros_ws/src/launch_ros_sandbox/coverage.xml
        flags: unittests
        name: codecov-umbrella
        # codecov sometimes fail to upload the report, this
        # leads to flaky build failures.
        # In the future, it may be interesting to have a separate
        # job for coverage reports with a higher tolerance for failure
        # and/or add retry logic to the action.
        fail_ci_if_error: false
    - uses: actions/upload-artifact@v2.3.0
      with:
        name: colcon-logs-ubuntu
        path: ros_ws/log
